# Generated by Django 2.0.5 on 2018-06-18 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectemployee',
            old_name='employee_name',
            new_name='employee_email',
        ),
    ]
