# Generated by Django 2.0.5 on 2018-06-19 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20180618_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectemployee',
            name='employee_email',
        ),
        migrations.AddField(
            model_name='projectemployee',
            name='employee_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
