# Generated by Django 2.0.5 on 2018-06-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20180619_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectemployee',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
