# Generated by Django 2.0.5 on 2018-06-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180619_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('closed', 'closed')], max_length=30, verbose_name='status'),
        ),
    ]
