# Generated by Django 2.0.5 on 2018-06-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_task_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Play', 'Play'), ('Pause', 'Pause')], default=None, max_length=30, verbose_name='activity'),
        ),
    ]
