# Generated by Django 2.0.5 on 2018-06-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20180626_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Play', 'Play'), ('Pause', 'Pause')], default='1', max_length=30, verbose_name='activity'),
        ),
    ]
