# Generated by Django 2.0.5 on 2018-06-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20180627_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.CharField(blank=True, choices=[('Started', 'Started'), ('Play', 'Play'), ('Pause', 'Pause')], default='Started', max_length=30, verbose_name='activity'),
        ),
    ]
