# Generated by Django 2.0.5 on 2018-06-27 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20180627_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='start_date')),
                ('end_time', models.DateTimeField(blank=True, verbose_name='start_date')),
                ('total_time', models.DateTimeField(blank=True, verbose_name='start_date')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='activity',
            field=models.CharField(blank=True, choices=[('default', 'default'), ('Started', 'Started'), ('Play', 'Play'), ('Pause', 'Pause')], default='default', max_length=30, verbose_name='activity'),
        ),
        migrations.AddField(
            model_name='tasktime',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Task'),
        ),
    ]
