# Generated by Django 2.0.5 on 2018-06-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20180627_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktime',
            name='total_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_date'),
        ),
    ]
