# Generated by Django 2.0.5 on 2018-06-29 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20180628_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktime',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Task'),
        ),
    ]
