# Generated by Django 2.0.5 on 2018-06-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20180629_0553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktime',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end_time'),
        ),
        migrations.AlterField(
            model_name='tasktime',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start_time'),
        ),
        migrations.AlterField(
            model_name='tasktime',
            name='total_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='total_time'),
        ),
    ]
