# Generated by Django 2.0.5 on 2018-06-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_auto_20180629_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktime',
            name='total_time',
            field=models.DurationField(blank=True, null=True, verbose_name='total_time'),
        ),
    ]
