# Generated by Django 2.0.5 on 2018-06-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_auto_20180629_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='total_time',
        ),
        migrations.AddField(
            model_name='tasktime',
            name='total_time',
            field=models.DurationField(blank=True, null=True, verbose_name='total_time'),
        ),
    ]
