# Generated by Django 2.0.5 on 2018-07-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20180629_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdetails',
            name='end_date',
            field=models.DateField(blank=True, verbose_name='end_date'),
        ),
        migrations.AlterField(
            model_name='projectdetails',
            name='start_date',
            field=models.DateField(blank=True, verbose_name='start_date'),
        ),
    ]
